#!/bin/sh

ROOTDIR="$(readlink -f $(dirname $0))"
. $ROOTDIR/test/ip_helper.sh

sudo -v
sudo redir --lport 80  --cport 80  --caddr $reverseproxy &
sudo redir --lport 443 --cport 443 --caddr $reverseproxy &

cleanup() {
  sudo pkill -9 redir
}

echo "Forwarding ports 80 and 443"
echo "Hit ctrl-c to stop"
echo "Browse to: https://softwarepublico.dev/"
echo "Browse to: https://listas.softwarepublico.dev/"
echo
trap cleanup INT TERM
tail -f /dev/null
echo
