#!/bin/sh

# MANAGED WITH CHEF; DO NOT CHANGE BY HAND

set -e

if [ $# -ne 1 ]; then
  echo "usage: $0 MODULE.te"
  exit 1
fi

selinux_status=$(sestatus | sed -e '/^SELinux status:/ !d; s/.*\s//')
if ! selinux-enabled; then
  echo "I: SELinux disabled, skipping"
  exit 0
fi

input="$1"

directory=$(dirname "$input")

cd $directory

module=$(basename --suffix=.te "$input")

rm -f ${module}.mod ${module}.pp

checkmodule -M -m -o ${module}.mod ${module}.te
semodule_package -o ${module}.pp -m ${module}.mod
semodule -i ${module}.pp
