# autogenerated DNS documentation

SPB_ENV ?= local

BUILT += dns.rst
dns.rst: ../test/dns_test.sh
	(cd .. && sh test/dns_test.sh --doc) > $@

BUILT += arquitetura.png
%.png: %.svg
	inkscape --export-area-page --export-width=800 --export-width=600 --export-png=$@ $<

BUILT += $(patsubst %.in, %, $(wildcard *.in))
%: %.in build.rb
	ruby -p build.rb $< > $@ || ($(RM) $@; false)

CLEAN_FILES += $(BUILT)
