# autogenerated DNS documentation

BUILT += dns.rst

dns.rst: ../test/dns_test.sh
	(cd .. && sh test/dns_test.sh --doc) > $@

BUILT += architecture.png

architecture.png: architecture.dot
	dot -Tpng -o $@ $<


CLEAN_FILES += $(BUILT)
